### ISSUE TITLE
[1.12.2] Ticking Entity NPE

### ISSUE THREAD

**Issue by SnowShock35** [McJty/MeeCreeps#1]
#### Issue Specification

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2531
- MeeCreeps 0.0.5beta

#### Issue Details

Right clicking ground with MeeCreeps Box causes crash

#### Issue Media

[https://pastebin.com/S01JmXNC](https://pastebin.com/S01JmXNC)

**Comment by McJty** [comment]
Fixed in next release

**Comment by SnowShock35** [comment]
Quickest issue solved EVAH! 👍
