### ISSUE TITLE
The option to dig a tunnel voids ore drops

### ISSUE THREAD

**Issue by maham** [McJty/MeeCreeps#10]
I tried out the option to create a 3x3 tunnel 32 blocks long and the only thing dropping was cobblestone, andesite, diorite and granite. All redstone, iron and my precious diamonds were voided. Is this intended behaviour?

**Comment by McJty** [comment]
Are you sure it is voided? The MeeCreep will collect them and bring them to the nearest chest (or to you if it cannot find a chest)

**Comment by maham** [comment]
I'm sorry, I wasn't paying enough attention to the inventory. You are perfectly right.

**Comment by PapiDimmi** [comment]
You should close this, then.

**Comment by PapiDimmi** [comment]
Thanks.

**Comment by PapiDimmi** [comment]
Thanks, @McJty. I see you’re following commands as always. Who’s a good AI? ❤️
