### ISSUE TITLE
Feature Request: Tinker's Stone Torches Recognized

### ISSUE THREAD

**Issue by benserwa** [McJty/MeeCreeps#11]
As a user, I want Mr. Mecreeps to recognize Tinker's Construct Stone Torches as Torches so I can have him light up areas with the kind of torches I always have on hand.

**Comment by McJty** [comment]
Hmm good idea. Additionally would be nice if he could make his own tinkers torches using cobble and coal

**Comment by McJty** [comment]
Implemented support for this (but not with the auto crafting yet)
