### ISSUE TITLE
World corruption when trying to make it build a 13x13 house

### ISSUE THREAD

**Issue by Boqzo1** [McJty/MeeCreeps#12]
So I've filled a chest with glass, torches, and cobblestone (has a tiny progressions cobble gen under it), then tried to make the MeeCreep build a 13x13 house and the game crashes and no longer lets me into the world. I don't feel like I'm doing anything out of the ordinary to cause this issue so hopefully it's a simple fix :)
[crash-2017-11-24_14.03.41-server.txt](https://github.com/McJty/MeeCreeps/files/1502408/crash-2017-11-24_14.03.41-server.txt)

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Ok, this is actually a bug in another mod as it is returning null itemstacks. I will fix it so MeeCreeps can handle it but I will add a message to the log indicating what mod is at fault here

**Comment by McJty** [comment]
Can you tell me what modded inventories you have nearby?

**Comment by McJty** [comment]
0.1.6beta will have protection for badly behaving mods
