### ISSUE TITLE
question

### ISSUE THREAD

**Issue by CharCharthemonkey** [McJty/MeeCreeps#13]
umm will meecreeps work in peaceful? i ask cause tried to get them to flatten a 13x13 area and it did maybe 2 blocks then sizzeled so is this a bug or did i derp?

**Comment by McJty** [comment]
They work in peaceful. Note that flatten only removes blocks. They will not build up to flatten the area

**Comment by CharCharthemonkey** [comment]
well noted but unless i derped badly (which is possible) they keep sizzeling out in peaceful

**Comment by McJty** [comment]
If they were marked as hostile mobs they wouldn't even spawn in the first place. Did you try other tasks? Also how are you flattening the area? You need to right click the box on the height that you want to flatten

**Comment by CharCharthemonkey** [comment]
well the only tasks i tried was idle and flatten but only idle worked flatten maybe did as said above but thats all lol so im betting i did something derpy

**Comment by McJty** [comment]
Show me a screenshot of the area you tried

**Comment by CharCharthemonkey** [comment]
![2017-11-26_01 45 48](https://user-images.githubusercontent.com/30783285/33238111-b5b1c652-d24b-11e7-8f5f-e5fed7a20419.png)
![2017-11-26_01 45 57](https://user-images.githubusercontent.com/30783285/33238112-b61e3698-d24b-11e7-9f62-23902e64c431.png)
this is the area i tried it did at most maybe 3 blocks

**Comment by McJty** [comment]
Well it already looks flat to me? Sorry but you need to be much more clear. Exactly on what block did you right click the mee creep cube? What area did you expect to be flattened? It is hard to debug from a distance so I need as much info as you can give me.

**Comment by CharCharthemonkey** [comment]
i needed it to do a 13x13 area right clicked on the bottom right block and it did maybe 1-2 blocks max most of that was flattened by me not the meecreep

**Comment by McJty** [comment]
The block you have to select is the center of the area

**Comment by CharCharthemonkey** [comment]
ok so then it was my derp not an actual bug for y it wasnt working ok ty buchnes
