### ISSUE TITLE
pick up and follow me across dimensions is a disaster area

### ISSUE THREAD

**Issue by cpw** [McJty/MeeCreeps#14]
If you ask a meecreeps (or several) to "pick up a chest and follow me" and then cross into a new dimension (tested with @aroma1997's mining world) the meecreeps kinda derp out a lot - getting stuck in terrain and dying and stuff. The chests are either randomly deposited in the original dimension, or are lost entirely.

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Will be fixed next release. I think I managed to solve all the kinks and weird things
