### ISSUE TITLE
MeeCreeps can only build

### ISSUE THREAD

**Issue by 132ikl** [McJty/MeeCreeps#15]
I am running the DW20 1.12 pack version 1.1 (current stable) on a server. MeeCreeps are able to build, but aren't able to do any other action. If you quickly punch them after clicking the menu option, they will occasionally begin to perform that task but fail to complete it (ex. only chops one block of a tree).

**Comment by McJty** [comment]
First what version of MeeCreeps is this?
Secondly what kind of tree are you trying this on?
