### ISSUE TITLE
Meecreeps vs. Destabilised Redstone

### ISSUE THREAD

**Issue by uecasm** [McJty/MeeCreeps#16]
Meecreeps 0.1.7 in the DW20 1.12.2 pack.

Summoned one to dig a 3x3 tunnel, and it ran into a pocket of Destabilised Redstone ore (from one of the Thermal mods).  This ore causes fluid flow when broken (though it usually disappears on its own) but it also sometimes spawns with a pocket of liquid already in-world.

The Meecreep is now stuck apparently trying to mine the flowing fluid blocks (I guess it doesn't recognise the fluid?) and not actually making any progress.  Interestingly it also doesn't seem to be despawning based on a time limit either.

I placed some extra blocks to kill the fluid source blocks and it was then able to continue mining, ~but it didn't drop any of the destabilised redstone ore blocks (as usually happens when you mine manually).  It's possible this is intended by Thermal, though.~ (Apparently they're not dropping any ores at all, only basic stone-based blocks like cobble and granite.  Is that intended?)

**Comment by McJty** [comment]
This is not really a bug. MeeCreeps are not supposed to be perfect. They are early game helpers

**Comment by McJty** [comment]
About the ores. They don't drop ores but give them to you (or nearby chest) if they are finished

**Comment by uecasm** [comment]
Direwolf mentioned that they could deal with water and lava though, so why not any other fluid?  Either just replace it (since most in-world fluids aren't valuable) or just give up.   (I did notice they would refuse to dig any further when the next block dug would drop lava on their head..)

I didn't try placing a chest, but I don't think I received ores from one, at least not during that run.  I'll have to double check that.  There was an old spawner room somewhat nearby (~64 blocks) which might have still had a chest in it, maybe it went over there instead?

**Comment by McJty** [comment]
They can deal with liquids to some extent. But they are not perfect even with water and lava. And yes, it is possible it used that chest. It will try to find any chest nearby and if that fails give the stuff to you directly

**Comment by Ozzymud** [comment]
I had this happen to me once on DW20 already, there was a vanilla dungeon within a few blocks of the tunnel and I later found a bunch of ore in one of its chests. Maybe have them only check within a few blocks of their start position?

**Comment by McJty** [comment]
I have a better idea. I'll let the MeeCreep give you a message when it is done telling you where it left its loot (in the sense of: 'I dropped of some stuff for you in a chest at 'XXX' distance')

**Comment by McJty** [comment]
This is now implemented
