### ISSUE TITLE
MeeCreeps destroys existing blocks in work areas for torch lighting

### ISSUE THREAD

**Issue by Vaygrim** [McJty/MeeCreeps#2]
![screenshot 2017-11-11 18 35 17](https://user-images.githubusercontent.com/4295188/32694868-47171796-c711-11e7-8c9c-d6aa482db18d.png)

This is one of the stone walls used to fence off raised areas, automatically generated by Lost Cities worldgen. They get 'destroyed' (as in I didn't see the block itself drop when broke) and replaced with torches when you use the command "Light up the area".

Maybe have the torch get put on TOP of the wall, if it can detect such things?

**Comment by McJty** [comment]
Hmm weird. I'll check out what's up with that

**Comment by McJty** [comment]
Fixed next release
