### ISSUE TITLE
Flatten area doesn't work in claimed chunks

### ISSUE THREAD

**Issue by liwanu** [McJty/MeeCreeps#23]
Playing the Direwolf20 Modpack v 1.2.0, updated Meecreeps to "meecreeps-1.12-1.0.1".
I dug down 10 blocks then asked meecreeps to flatten out an area, he just stood there indefinitely. I unclaimed the chunk and tried again, he started clearing out the area.

**Comment by McJty** [comment]
Check with FTB Utilities. MeeCreeps uses a fake player and you have to give that permission somehow.
