### ISSUE TITLE
No it dont - The chop trees action should work on modded trees too 

### ISSUE THREAD

**Issue by ashly138** [McJty/MeeCreeps#3]
In the latest version chopping trees on vanila trees works fine but the modded ones it only seams to chop down the bottum log and than the meecreep just goes away. Leaving Floating tree haha

EDIT: Pam's Harvestcraft & natura Trees dont even get an option for the meecreep to chop tree yet.

**Comment by McJty** [comment]
Fixed next release (for Forestry at least)
