### ISSUE TITLE
Mod Interaction w/ Actually Additions Causing Duplication of Blocks

### ISSUE THREAD

**Issue by SnowShock35** [McJty/MeeCreeps#30]
#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2583
- McJtyLib 2.6.2
- MeeCreeps 1.1.0
- Other Mods:
  - Actually Additions 1.12.2-r126

#### Issue Description

When told to flatten an area (Not tried with other commands.) MeeCreeps will destroy actually additions blocks however somehow two of them will be dropped. Giving you an easy way to duplicate items.

I have speculation that this is related to `getDrops()` but that's just speculation.

#### Issue Media

https://imgur.com/rZPbuHu

**Comment by McJty** [comment]
Have you also reported this to Actually Additions? I'm using the normal block harvesting rules so if that's somehow duplicating things then that can also be a bug on their side

**Comment by SnowShock35** [comment]
I was literally just doing it 😜

**Comment by SnowShock35** [comment]
Also reported to Actually Additions Issue Tracker [Ellpeck/ActuallyAdditions#998](https://github.com/Ellpeck/ActuallyAdditions/issues/998)

**Comment by McJty** [comment]
https://github.com/McJty/MeeCreeps/blob/master/src/main/java/mcjty/meecreeps/actions/workers/WorkerHelper.java#L669

**Comment by canitzp** [comment]
The little problem is that you're getting the list of drops, then block.onBlockHarvest and after that you drop the drops. The actually additions container does drop themself in the block.onBlockHarvest method, so there are finally two drops.

**Comment by McJty** [comment]
I don't think you're supposed to do that this way. Why not return the drops in getDrops()?

**Comment by SnowShock35** [comment]
@canitzp To answer your question it's every block from what I can see.

**Comment by McJty** [comment]
@SnowShock35 Every block of AA I suppose?

**Comment by SnowShock35** [comment]
Yeah, Every Block in AA.

**Comment by McJty** [comment]
To @canitzp 

    /**
     * Called before the Block is set to air in the world. Called regardless of if the player's tool can actually
     * collect this block
     */
    public void onBlockHarvested(World worldIn, BlockPos pos, IBlockState state, EntityPlayer player)
    {
    }

That means this is called even if the block will not actually get broken (i.e. if the tool cannot collect it) and you wouldn't want to produce drops then

**Comment by canitzp** [comment]
I'll take a look into changing the method

**Comment by canitzp** [comment]
I wrote to Ellpeck and he means that at the time he wrote the code, the hacky method was the only way of doing it. He have looked at several other mods too. I now have the problem that you don't call block.harvestBlock, so my fix wouldn't work. How do you write nbt to the drop stacks from the tileentity?

**Comment by McJty** [comment]
Here is how I solve this in McJtyLib (delaying the removal of the TE until after getDrops):

https://github.com/McJty/McJtyLib/blob/1.12/src/main/java/mcjty/lib/container/GenericBlock.java#L235-L264

**Comment by canitzp** [comment]
I now changed the actadd code according to the example you gave me and it does work, so MeeCreeps should now work fine with actadd machines

**Comment by McJty** [comment]
Thanks!
