### ISSUE TITLE
Meseeks dupe bug

### ISSUE THREAD

**Issue by NightbringerMc** [McJty/MeeCreeps#4]
Ok, so I basically launched Direwolf20 v1.12.2 (Modpack v 1 I think)
and when I logged on a server to test the mod (I'm a staff member of said server)
I realised that Mr Meseeks duped any item he tries to break (See screenshot)
We have claim plugins on the server so of course I teleported away from the claim and tried, and got the same result...
![unknown](https://user-images.githubusercontent.com/11724469/32865498-b4b91ccc-ca63-11e7-9fee-593dda5bf252.png)
![unknown 1](https://user-images.githubusercontent.com/11724469/32865511-bfa9872a-ca63-11e7-9aa8-ea487dd1f2ad.png)
The second picture was tried with the 9x9 function and the 11x11 function ("Build a house")

I hope I am of any help with this report, and that this bug is easy to fix, since the mod seems really fun :)

**Comment by McJty** [comment]
Hmm, what about ftb utilities?

**Comment by McJty** [comment]
Could you try again with latest release (0.1.2)? Thanks

**Comment by NightbringerMc** [comment]
I'll get to it this afternoon when I get access to my computer.
Also, we have FTB Utils disabled on all of our servers (Messes with our claiming plugin)

**Comment by NightbringerMc** [comment]
It fixes it (V.0.1.2)  :)

**Comment by McJty** [comment]
Nice!
