### ISSUE TITLE
Crash When chopping down tree (Dw20 pack)

### ISSUE THREAD

**Issue by gigabit101** [McJty/MeeCreeps#5]
I think he was trying to put items into a chest I just removed to replace https://gist.github.com/gigabit101/86f31f13e68b95596d3e2d3b3d38e8b1

**Comment by McJty** [comment]
What exactly did you do to reproduce this?

**Comment by gigabit101** [comment]
1. Get a meecreep to chop down a tree (Keep Inv)
2. Break the inventory he is going to put items into while he is walking over to it

This seems like a very unlikely bug for people 2 encounter lol

**Comment by McJty** [comment]
Still it is a bug. I'll fix it

**Comment by McJty** [comment]
Fixed in next release
