### ISSUE TITLE
Portal Bug

### ISSUE THREAD

**Issue by NightbringerMc** [McJty/MeeCreeps#6]
Hey again !
I just got an issue with the portals from the Meecreeps mod, where I placed a portal down and it did not despawn and played the sound over and over again.
Is there a way to remove the portals using a command /Item other that the gun?
![2017-11-16_20 35 17](https://user-images.githubusercontent.com/11724469/32912062-3ca7d588-cb0e-11e7-9bca-f449cc78cd0b.png)

**Comment by NightbringerMc** [comment]
And also it repeatedly crashes the server when a portal is sent (I have not tested enough to know the reason)

**Comment by McJty** [comment]
For the crash I will need a crashlog.

Right clicking a portal with the gun should remove it
