### ISSUE TITLE
MeeCreeps can break any mine-able blocks early.

### ISSUE THREAD

**Issue by ariosos** [McJty/MeeCreeps#7]
Tried posting in the comments section, but didn't seem to want to post. Testing it without any other mods - was able to have it clear out an area and mine obsidian and diamond ore.

**Comment by McJty** [comment]
yes, that's normal. It can mine anything that you can mine with a diamond pickaxe

**Comment by McJty** [comment]
(note that to make the Creep Cube you need diamonds, so the player will also be able to mine diamonds already)
