### ISSUE TITLE
Crash when using JER profile command?

### ISSUE THREAD

**Issue by LocalBoomer** [McJty/MeeCreeps#72]
So I ran the command /jer_profile 1 all and the game crashed, seems fair I had no idea what I was doing and using an all parameter might be too much but the crash referenced your library mod and MeeCreeps... O_o

https://pastebin.com/96wKe1hM

MC: 1.12.2
forge: 14.23.5.2847     
mcjtylib: 3.5.4
meecreeps: 1.3.1

**Comment by McJty** [comment]
Hmm not sure why that would happen but that does seem to be a bug in JER though. I'm not doing anything wrong there as far as I know

**Comment by ghost** [comment]
still an issue

**Comment by McJty** [comment]
Still a bug in JER.
Also I no longer work on 1.12.2
